config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'items#index'
  get 'mypage', to: 'static_pages#mypage'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  resources :users, only: [:show] do
    resources :evalutions, only: [:index]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  scope :user do
    resources :point_histories
    resources :drafts, only: %i[index show]
  end

  scope :point do
    resource :purchase
  end

  resources :likes, only: %i[create destroy]
  resources :items, only: %i[index show create destroy edit new update] do
    resource :procedure, only: %i[show create] do
      member do
        post :add_address
      end
    end
    resource :contact, only: [:show] do
      member do
        post :change_status
        post :evaluate_user
      end
    end
    
    resources :comments, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def mypage
    @user = current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/mypage.html.haml
.container
  - if user_signed_in?
    %ul.list-group
      %li.list-group-item= link_to 'ログアウト', destroy_user_session_path, method: :delete
      %li.list-group-item= link_to '更新', edit_user_registration_path
      %li.list-group-item= link_to 'ポイント購入', purchase_path
      %li.list-group-item= link_to 'ポイント履歴', point_histories_path
      %li.list-group-item= link_to 'アイテム新規作成', new_item_path
      %li.list-group-item= link_to 'マイページ', user_path(current_user.id)
      %li.list-group-item= link_to '下書き一覧', drafts_path