config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'items#index'
  get 'mypage', to: 'static_pages#mypage'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  resources :users, only: [:show] do
    resources :evalutions, only: [:index]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  scope :user do
    resources :point_histories
    resources :drafts, only: %i[index show]
  end

  scope :point do
    resource :purchase
  end

  resources :likes, only: %i[create destroy]
  resources :items, only: %i[index show create destroy edit new update] do
    resource :procedure, only: %i[show create] do
      member do
        post :add_address
      end
    end
    resource :contact, only: [:show] do
      member do
        post :change_status
        post :evaluate_user
      end
    end
    
    resources :comments, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                   :bigint           not null, primary key
#  images               :json
#  include_shipping_fee :boolean
#  item_status          :integer
#  name                 :string
#  price                :integer
#  text                 :text
#  transaction_status   :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  buyer_address_id     :bigint
#  buyer_id             :bigint
#  category_id          :bigint
#  user_id              :bigint
#
# Indexes
#
#  index_items_on_category_id  (category_id)
#  index_items_on_user_id      (user_id)
#
class Item < ApplicationRecord
  mount_uploaders :images, ImageUploader
  serialize :images
  ## validation
  belongs_to :user
  belongs_to :buyer, optional: true, class_name: 'User'
  belongs_to :category
  belongs_to :buyer_address, foreign_key: 'buyer_address_id', optional: true, class_name: 'Address'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :evalutions
  validates :price, presence: true, numericality: { greater_than: 5 }
  validates :name, presence: true
  validates :transaction_status, presence: true
  validates :item_status, presence: true
  validates :text, length: { maximum: 1000 }
  validates :include_shipping_fee, default: false
  ## define enum
  enum transaction_status: { draft: 0, sale: 1, shipping: 2, wait_sender_review: 3, wait_recever_review: 4, sold_out: 5, hidden: 6 }
  enum item_status: { new: 0, like_new: 1, good: 2, fair: 3, poor: 4 }, _prefix: true
  ## scope
  scope :sales, -> { where(transaction_status: :sale) }
  scope :drafts, -> { where(transaction_status: :draft) }
  scope :not_drafts, -> { where.not(transaction_status: :draft) }
  scope :sold_outs, -> { where.not(transaction_status: :sale).where.not(transaction_status: :draft) }
  scope :displays, -> { where.not(transaction_status: :draft).where.not(transaction_status: :hidden) }

  def point_buy(purchaser)
    self.buyer = purchaser
    self.transaction_status = :shipping
    save
    buyer.point -= price
    buyer.save
    PointBuyHistory.create(user: buyer, date: DateTime.now, parent_id: id, point: -price)
  end

  def point_transfer
    user.point += price
    user.save
    PointSellHistory.create(user: user, date: DateTime.now, parent_id: id, point: price)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = Item.where.not(transaction_status: :draft)
  end

  def new
    @item = Item.new
    @categories = Category.all
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if params[:draft_submit]
      @item.assign_attributes(transaction_status: :draft)
      @item.save(validate: false)
      redirect_to items_path
    elsif params[:submit]
      @item.assign_attributes(transaction_status: :sale)
      if @item.save
        redirect_to item_path(@item.id)
      else
        @categories = Category.all
        render 'new'
      end
    end
  end

  def show
    @item = Item.displays.find(params[:id])
    @comments = @item.comments
  end

  def update
    @categories = Category.all
    @item = Item.find(params[:id])

    if params[:draft_submit]
      @item.assign_attributes(item_params)
      @item.assign_attributes(transaction_status: :draft)
      @item.save(validate: false)
      redirect_to @item
    elsif @item.update(item_params)
      @item.sale!
      redirect_to @item
    else
      render 'edit'
    end
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def destroy
    @item = Item.find(params[:id])
    redirect_to items_path if @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:category_id, :price, :name, :transaction_status, :include_shipping_fee, :text, :item_status, { images: [] })
  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/edit.html.haml
= form_with model: @item, local: true do |f|
  .form-group
    = f.label :name
    %br
    = f.text_field :name
  .form-group
    = f.label :text
    %br
    = f.text_area :text
  .form-group
    = f.label :transaction_status
    %br
    = f.select :transaction_status, options_for_select(Item.transaction_statuses.keys)
  .form-group
    = f.label :item_status
    %br
    = f.select :item_status, options_for_select(Item.item_statuses.keys)
  .form-group
    = f.label :price
    %br
    = f.text_field :price
  .form-group
    = f.label :category
    %br
    = f.select :category_id, @categories.map{ |category| [category.name, category.id] }
  .form-group
    = f.label :include_shipping_fee
    %br
    = f.check_box(:include_shipping_fee)
  .form-group
    = f.file_field :images, multiple: true
  = f.submit '出品する', name: 'submit'
  = f.submit '下書きに保存', name: 'draft_submit'
= link_to '一覧に戻る', items_path

app/views/items/index.html.haml
.container
  - if user_signed_in?
    %ul.list-group
      %li.list-group-item= link_to 'Mypage', mypage_path
    %h2 商品一覧
    %ul.list-group
      - @items.each do |item|
        %li.list-group-item= link_to "#{item.name}", item_path(item)

app/views/items/new.html.haml
= form_with model: @item, local: true do |f|
  .form-group
    = f.label :name
    %br
    = f.text_field :name
  .form-group
    = f.label :text
    %br
    = f.text_area :text
  .form-group
    = f.label :item_status
    %br
    = f.select :item_status, options_for_select(Item.item_statuses.keys)
  .form-group
    = f.label :price
    %br
    = f.text_field :price
  .form-group
    = f.label :category
    %br
    = f.select :category_id, @categories.map{ |category| [category.name, category.id] }
  .form-group
    = f.label :include_shipping_fee
    %br
    = f.check_box(:include_shipping_fee)
  .form-group
    = f.file_field :images, multiple: true
  = f.submit '出品する', name: 'submit'
  = f.submit '下書きに保存', name: 'draft_submit'
= link_to '一覧に戻る', items_path

app/views/items/show.html.haml
%h2= @item.name
%ul
  %li= link_to"出品者 #{@item.user.name}", user_path(@item.user.id)
  %li= "カテゴリー #{@item.category.name}"
  %li= "transaction_status #{@item.transaction_status}"
  %li= "商品の状態 #{@item.item_status}"
  - if @item.include_shipping_fee == true
    - fee= "送料込み(出品者負担)"
  - else
    - fee= "送料別(購入者負担)"
  %li= "送料の負担 #{fee}"
  %li= "#{@item.price}円"
%p= @item.text
- @item.images.each do |image|
  = image_tag image.url
- unless @item.likes.exists?(user_id: current_user.id)
  = button_to 'いいね', likes_path(id: @item.id), method: :post
- else
  %p いいね済
  = button_to 'いいねの取り消し', like_path(@item), method: :delete

= form_with url: item_comments_path(@item), local: true do |f|
  = f.label :text
  %br
  = f.text_area :text
  %br
  = f.submit 'コメントする'
- @comments.each do |comment|
  %p= comment.text
  - if comment.user_id == current_user.id
    = button_to '削除', item_comment_path(@item,comment), method: :delete
%br
- if @item.user_id == current_user.id
  = button_to "編集", edit_item_path(@item), method: :get
  = button_to "削除", item_path(@item), method: :delete, data: { confirm: "are you sure?" }
= link_to '一覧に戻る', items_path
- if (@item.user_id != current_user.id) && @item.transaction_status == "sale"
  = button_to "購入", item_procedure_path(@item), method: :get
- if @item.buyer != nil && (current_user.id == @item.buyer_id || current_user.id == @item.user_id )
  = button_to "詳細画面へ", item_contact_path(@item), method: :get