config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'items#index'
  get 'mypage', to: 'static_pages#mypage'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  resources :users, only: [:show] do
    resources :evalutions, only: [:index]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  scope :user do
    resources :point_histories
    resources :drafts, only: %i[index show]
  end

  scope :point do
    resource :purchase
  end

  resources :likes, only: %i[create destroy]
  resources :items, only: %i[index show create destroy edit new update] do
    resource :procedure, only: %i[show create] do
      member do
        post :add_address
      end
    end
    resource :contact, only: [:show] do
      member do
        post :change_status
        post :evaluate_user
      end
    end
    
    resources :comments, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :authenticate_user!
  def create
    @item = Item.find(params[:item_id])
    if current_user.id == @item.user_id
      redirect_to item_path(@item)
      return
    end

    @address = current_user.addresses.find(params[:address][:id])
    if @item.buyer.present?
      redirect_to item_path(@item)
      return
    end

    @item.buyer_address = @address

    if current_user.point < @item.price
      redirect_to item_path(@item)
      return
    end
    @item.point_buy(current_user)
    @item.save
    redirect_to item_contact_path(@item)
  end

  def show
    @item = Item.find(params[:item_id])
    @address = current_user.addresses.build
  end

  def add_address
    @item = Item.find(params[:item_id])
    @address = current_user.addresses.build(address_params)
    @address.save
    redirect_to item_procedure_path(@item)
  end

  private

  def address_params
    params[:address].permit(:id, :zipcode, :prefecture_num, :address1, :address2, :name, :phone_number)
  end
end

app/helpers/procedure_helper.rb
module ProcedureHelper
end

app/views/procedures/show.html.haml
= form_with model: @address, url: add_address_item_procedure_path(@item), local: true do |f|
  .form-group
    = f.label :zipcode
    %br
    = f.text_field :zipcode
  .form-group
    = f.label :prefecture_num
    %br
    =  f.select :prefecture_num, Address.prefecture_nums.keys
  .form-group
    = f.label :address1
    %br
    = f.text_field :address1
  .form-group
    = f.label :address2
    %br
    = f.text_field :address2
  .form-group
    = f.label :name
    %br
    = f.text_field :name
  .form-group
    = f.label :phone_number
    %br
    = f.text_field :phone_number
  %br
  = f.submit
  /既存の住所がある場合は、プルダウンメニューで選択できるようにする
= form_with model: @address, url: item_procedure_path(@item), local: true do |f|
  .form-group
    = f.label :id
  %br
    = f.collection_select :id, Address.where(user: current_user), :id, :address_info
  = f.submit
    