config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'items#index'
  get 'mypage', to: 'static_pages#mypage'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  resources :users, only: [:show] do
    resources :evalutions, only: [:index]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  scope :user do
    resources :point_histories
    resources :drafts, only: %i[index show]
  end

  scope :point do
    resource :purchase
  end

  resources :likes, only: %i[create destroy]
  resources :items, only: %i[index show create destroy edit new update] do
    resource :procedure, only: %i[show create] do
      member do
        post :add_address
      end
    end
    resource :contact, only: [:show] do
      member do
        post :change_status
        post :evaluate_user
      end
    end
    
    resources :comments, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :authenticate_user!
  def index
    @drafts = current_user.items.where(transaction_status: :draft)
  end

  def show
    @item = current_user.items.find(params[:id])
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/index.html.haml
- if @drafts.present?
  - @drafts.each do |item|
    %ul
      %li= link_to "#{item.name}", draft_path(item.id)
- else
  %p 下書きはありません

app/views/drafts/show.html.haml
%h2= @item.name
%ul
  %li="出品者 #{@item.user.name}"
  %li= "カテゴリー #{@item&.category&.name}"
  %li= "商品の状態 #{@item.item_status}"
  - if @item.include_shipping_fee == true
    - fee= "送料込み(出品者負担)"
  - else
    - fee= "送料別(購入者負担)"
  %li= "送料の負担 #{fee}"
  %li= "#{@item.price}円"
%p= @item.text
- @item.images.each do |image|
  = image_tag image.url

- if @item.user_id == current_user.id
  = button_to "編集", edit_item_path(@item), method: :get
  = button_to "削除", item_path(@item), method: :delete, data: { confirm: "are you sure?" }
= link_to '一覧に戻る', items_path